// This file is auto-generated by generate-logo-map.js. Do not edit manually.
import adobeCcLogo from "@/assets/logos/adobe-cc.png";
import anytimeInventLogo from "@/assets/logos/anytime-invent.png";
import apifyCreditsLogo from "@/assets/logos/apify-credits.png";
import apifyLogo from "@/assets/logos/apify.svg";
import awsCreditsLogo from "@/assets/logos/aws-credits.png";
import boltLogo from "@/assets/logos/bolt.png";
import canvaProLogo from "@/assets/logos/canva-pro.png";
import chatgptProLogo from "@/assets/logos/chatgpt-pro.png";
import cloudProLogo from "@/assets/logos/cloud-pro.png";
import courseraLogo from "@/assets/logos/coursera.svg";
import cursorProLogo from "@/assets/logos/cursor-pro.png";
import cursorLogo from "@/assets/logos/cursor.svg";
import copilotLogo from "@/assets/logos/github-copilot.svg";
import manusLogo from "@/assets/logos/manus.svg";
import descriptLogo from "@/assets/logos/descript.svg";
import elementsLogo from "@/assets/logos/elements.png";
import figmaLogo from "@/assets/logos/figma.png";
import gammaProLogo from "@/assets/logos/gamma-pro.png";
import githubLogo from "@/assets/logos/github.png";
import hootsuiteLogo from "@/assets/logos/hootsuite.png";
import invideoLogo from "@/assets/logos/invideo.png";
import itnLogo from "@/assets/logos/itn.png";
import levelProLogo from "@/assets/logos/level-pro.png";
import linkedinPremiumLogo from "@/assets/logos/linkedin-premium.png";
import lovableProLogo from "@/assets/logos/lovable-pro.png";
import marqueeAirtableCreditsLogo from "@/assets/logos/marquee-airtable-credits.png";
import marqueeAirtableLogo from "@/assets/logos/marquee-airtable.png";
import airtableLogo from "@/assets/logos/airtable.svg";
import marqueeAsanaLogo from "@/assets/logos/marquee-asana.png";
import asanaLogo from "@/assets/logos/asana.svg";
import marqueeAutodeskLogo from "@/assets/logos/marquee-autodesk.png";
import autodeskLogo from "@/assets/logos/autodesk.svg";
import marqueeCanvaBusinessLogo from "@/assets/logos/marquee-canva-business.png";
import marqueeCapcutProLogo from "@/assets/logos/marquee-capcut-pro.png";
import marqueeChatprdLogo from "@/assets/logos/marquee-chatprd.png";
import marqueeCoderabbitProLogo from "@/assets/logos/marquee-coderabbit-pro.png";
import marqueeCustomerIoLogo from "@/assets/logos/marquee-customer-io.png";
import marqueeDescriptLogo from "@/assets/logos/marquee-descript.png";
import marqueeDisneyPlusLogo from "@/assets/logos/marquee-disney-plus.png";
import marqueeEdxTeamsLogo from "@/assets/logos/marquee-edx-teams.png";
import edxLogo from "@/assets/logos/edx.svg";
import marqueeFactoryLogo from "@/assets/logos/marquee-factory.png";
import factoryLogo from "@/assets/logos/factory.svg";
import marqueeFeatureFmLogo from "@/assets/logos/marquee-feature-fm.png";
import marqueeFilmoraLogo from "@/assets/logos/marquee-filmora.png";
import marqueeFirecrawlLogo from "@/assets/logos/marquee-firecrawl.png";
import marqueeFirefliesProLogo from "@/assets/logos/marquee-fireflies-pro.png";
import marqueeFramerProLogo from "@/assets/logos/marquee-framer-pro.png";
import framerLogo from "@/assets/logos/framer.svg";
import marqueeFreepikLogo from "@/assets/logos/marquee-freepik.png";
import marqueeGithubLogo from "@/assets/logos/marquee-github.png";
import linearLogo from "@/assets/logos/linear.svg";
import marqueeGranolaLogo from "@/assets/logos/marquee-granola.png";
import granolaLogo from "@/assets/logos/granola.png";
import marqueeGrokLogo from "@/assets/logos/marquee-grok.png";
import marqueeGuidlessProLogo from "@/assets/logos/marquee-guidless-pro.png";
import marqueeGumloopLogo from "@/assets/logos/marquee-gumloop.png";
import marqueeHiggsfieldLogo from "@/assets/logos/marquee-higgsfield.png";
import marqueeHootsuiteLogo from "@/assets/logos/marquee-hootsuite.png";
import marqueeHotstarLogo from "@/assets/logos/marquee-hotstar.png";
import marqueeIndyLogo from "@/assets/logos/marquee-indy.png";
import marqueeIntercomLogo from "@/assets/logos/marquee-intercom.png";
import marqueeLeadCmLogo from "@/assets/logos/marquee-lead-cm.png";
import marqueeLeonardoAiLogo from "@/assets/logos/marquee-leonardo-ai.png";
import marqueeLightfieldCrmLogo from "@/assets/logos/marquee-lightfield-crm.png";
import marqueeLinearLogo from "@/assets/logos/marquee-linear.png";
import marqueeLoomLogo from "@/assets/logos/marquee-loom.png";
import marqueeMagicpatternLogo from "@/assets/logos/marquee-magicpattern.png";
import marqueeMakeComLogo from "@/assets/logos/marquee-make-com.png";
import marqueeManusCreditsLogo from "@/assets/logos/marquee-manus-credits.png";
import marqueeManusProLogo from "@/assets/logos/marquee-manus-pro.png";
import marqueeMiroStarterLogo from "@/assets/logos/marquee-miro-starter.png";
import marqueeMobbinTeamLogo from "@/assets/logos/marquee-mobbin-team.png";
import marqueeMongodbCreditsLogo from "@/assets/logos/marquee-mongodb-credits.png";
import marqueeOpenaiCreditsLogo from "@/assets/logos/marquee-openai-credits.png";
import marqueeOtterAiLogo from "@/assets/logos/marquee-otter-ai.png";
import marqueePngtreeLogo from "@/assets/logos/marquee-pngtree.png";
import marqueePosthogLogo from "@/assets/logos/marquee-posthog.png";
import marqueePrimeVideoLogo from "@/assets/logos/marquee-prime-video.png";
import marqueeRailwayLogo from "@/assets/logos/marquee-railway.png";
import marqueeRaycastLogo from "@/assets/logos/marquee-raycast.png";
import raycastLogo from "@/assets/logos/raycast.svg";
import marqueeRenderCreditsLogo from "@/assets/logos/marquee-render-credits.png";
import marqueeReziLogo from "@/assets/logos/marquee-rezi.png";
import marqueeScalingoCreditsLogo from "@/assets/logos/marquee-scalingo-credits.png";
import marqueeSonyLivLogo from "@/assets/logos/marquee-sony-liv.png";
import marqueeSpeechifyLogo from "@/assets/logos/marquee-speechify.png";
import marqueeTextshiftLogo from "@/assets/logos/marquee-textshift.png";
import marqueeVapiCreditsLogo from "@/assets/logos/marquee-vapi-credits.png";
import vapiLogo from "@/assets/logos/vapi.svg";
import marqueeWarpbuildLogo from "@/assets/logos/marquee-warpbuild.png";
import warpbuildLogo from "@/assets/logos/warpbuild.svg";
import renderLogo from "@/assets/logos/render.svg";
import scalingoLogo from "@/assets/logos/scalingo.svg";
import marqueeYoutubePremiumLogo from "@/assets/logos/marquee-youtube-premium.png";
import marqueeZee5Logo from "@/assets/logos/marquee-zee5.png";
import msOfficeLogo from "@/assets/logos/ms-office.png";
import n8nLogo from "@/assets/logos/n8n.png";
import nordvpnLogo from "@/assets/logos/nordvpn.svg";
import notionBusinessLogo from "@/assets/logos/notion-business.png";
import openaiLogo from "@/assets/logos/openai.svg";
import perplexityLogo from "@/assets/logos/perplexity.svg";
import mongodbLogo from "@/assets/logos/mongodb.svg";
import replicaiLogo from "@/assets/logos/replicai.png";
import replitLogo from "@/assets/logos/replit.png";
import railwayLogo from "@/assets/logos/railway.svg";
import supabaseProLogo from "@/assets/logos/supabase-pro.png";
import whisperFlowLogo from "@/assets/logos/whisper-flow.png";
import grokLogo from "@/assets/logos/grok.svg";
import spotifyLogo from "@/assets/logos/spotify.svg";
import firecrawlLogo from "@/assets/logos/firecrawl.svg";
import claudeLogo from "@/assets/logos/claude.svg";
import v0Logo from "@/assets/logos/v0.svg";
import chatgptSvg from "@/assets/logos/chatgpt.svg";
import geminiSvg from "@/assets/logos/gemini.svg";
import elevenLabsSvg from "@/assets/logos/eleven-labs.svg";

export const LOGOS: Record<string, unknown> = {
  "adobe-cc": adobeCcLogo,
  "airtable": airtableLogo,
  "anytime-invent": anytimeInventLogo,
  "asana": asanaLogo,
  "autodesk": autodeskLogo,
  "apify-credits": apifyCreditsLogo,
  "apify": apifyLogo,
  "aws-credits": awsCreditsLogo,
  "bolt": boltLogo,
  "canva-pro": canvaProLogo,
  "chatgpt-plus": chatgptSvg,
  "chatgpt-pro": chatgptProLogo,
  "claude-pro": claudeLogo,
  "cloud-pro": cloudProLogo,
  "coursera": courseraLogo,
  "cursor-pro": cursorProLogo,
  "cursor": cursorLogo,
  "github-copilot": copilotLogo,
  "manus-pro": manusLogo,
  "descript": descriptLogo,
  "edx": edxLogo,
  "elements": elementsLogo,
  "eleven-labs": elevenLabsSvg,
  "factory": factoryLogo,
  "figma": figmaLogo,
  "framer": framerLogo,
  "granola": granolaLogo,
  "grok": grokLogo,
  "firecrawl": firecrawlLogo,
  "gamma-pro": gammaProLogo,
  "gemini-pro": geminiSvg,
  "github": githubLogo,
  "hootsuite": hootsuiteLogo,
  "invideo": invideoLogo,
  "itn": itnLogo,
  "level-pro": levelProLogo,
  "linkedin-premium": linkedinPremiumLogo,
  "linear": linearLogo,
  "lovable-pro": lovableProLogo,
  "marquee-airtable-credits": marqueeAirtableCreditsLogo,
  "marquee-airtable": marqueeAirtableLogo,
  "marquee-asana": marqueeAsanaLogo,
  "marquee-autodesk": marqueeAutodeskLogo,
  "marquee-canva-business": marqueeCanvaBusinessLogo,
  "marquee-capcut-pro": marqueeCapcutProLogo,
  "marquee-chatprd": marqueeChatprdLogo,
  "marquee-claude-credits": claudeLogo,
  "marquee-coderabbit-pro": marqueeCoderabbitProLogo,
  "marquee-customer-io": marqueeCustomerIoLogo,
  "marquee-descript": marqueeDescriptLogo,
  "marquee-disney-plus": marqueeDisneyPlusLogo,
  "marquee-edx-teams": marqueeEdxTeamsLogo,
  "marquee-factory": marqueeFactoryLogo,
  "marquee-feature-fm": marqueeFeatureFmLogo,
  "marquee-filmora": marqueeFilmoraLogo,
  "marquee-firecrawl": marqueeFirecrawlLogo,
  "marquee-fireflies-pro": marqueeFirefliesProLogo,
  "marquee-framer-pro": marqueeFramerProLogo,
  "marquee-freepik": marqueeFreepikLogo,
  "marquee-github": marqueeGithubLogo,
  "marquee-granola": marqueeGranolaLogo,
  "marquee-grok": marqueeGrokLogo,
  "marquee-guidless-pro": marqueeGuidlessProLogo,
  "marquee-gumloop": marqueeGumloopLogo,
  "marquee-higgsfield": marqueeHiggsfieldLogo,
  "marquee-hootsuite": marqueeHootsuiteLogo,
  "marquee-hotstar": marqueeHotstarLogo,
  "marquee-indy": marqueeIndyLogo,
  "marquee-intercom": marqueeIntercomLogo,
  "marquee-lead-cm": marqueeLeadCmLogo,
  "marquee-leonardo-ai": marqueeLeonardoAiLogo,
  "marquee-lightfield-crm": marqueeLightfieldCrmLogo,
  "marquee-linear": marqueeLinearLogo,
  "marquee-loom": marqueeLoomLogo,
  "marquee-magicpattern": marqueeMagicpatternLogo,
  "marquee-make-com": marqueeMakeComLogo,
  "marquee-manus-credits": marqueeManusCreditsLogo,
  "marquee-manus-pro": marqueeManusProLogo,
  "marquee-miro-starter": marqueeMiroStarterLogo,
  "marquee-mobbin-team": marqueeMobbinTeamLogo,
  "marquee-mongodb-credits": marqueeMongodbCreditsLogo,
  "marquee-openai-credits": marqueeOpenaiCreditsLogo,
  "marquee-otter-ai": marqueeOtterAiLogo,
  "marquee-pngtree": marqueePngtreeLogo,
  "marquee-posthog": marqueePosthogLogo,
  "marquee-prime-video": marqueePrimeVideoLogo,
  "marquee-railway": marqueeRailwayLogo,
  "marquee-raycast": marqueeRaycastLogo,
  "marquee-render-credits": marqueeRenderCreditsLogo,
  "marquee-rezi": marqueeReziLogo,
  "marquee-scalingo-credits": marqueeScalingoCreditsLogo,
  "marquee-sony-liv": marqueeSonyLivLogo,
  "marquee-speechify": marqueeSpeechifyLogo,
  "marquee-textshift": marqueeTextshiftLogo,
  "marquee-v0-credits": v0Logo,
  "marquee-vapi-credits": marqueeVapiCreditsLogo,
  "marquee-warpbuild": marqueeWarpbuildLogo,
  "marquee-youtube-premium": marqueeYoutubePremiumLogo,
  "marquee-zee5": marqueeZee5Logo,
  "ms-office": msOfficeLogo,
  "n8n": n8nLogo,
  "nordvpn": nordvpnLogo,
  "notion-business": notionBusinessLogo,
  "mongodb": mongodbLogo,
  "openai": openaiLogo,
  "perplexity": perplexityLogo,
  "replicai": replicaiLogo,
  "replit": replitLogo,
  "railway": railwayLogo,
  "raycast": raycastLogo,
  "spotify": spotifyLogo,
  "supabase-pro": supabaseProLogo,
  "whisper-flow": whisperFlowLogo,
  "warpbuild": warpbuildLogo,
  "vapi": vapiLogo,
  "render": renderLogo,
  "scalingo": scalingoLogo,
};
